// Server generated by gomarvin, v0.6.x
// Repo : https://github.com/tompston/gomarvin
// Docs : https://gomarvin.pages.dev/docs

package main

import (
	"backend/app"
	"backend/settings"
	"backend/settings/database"
	"fmt"
	"net/http"
)

func main() {

	address := fmt.Sprintf("localhost:%s", settings.GO_BACKEND_PORT)

	database.Connect() // set database.DB var to hold a connection to the db

	server := app.Start()
	http.ListenAndServe(address, server)

}
