// Code generated by gomarvin, v0.6.x. DO NOT EDIT.
// Rename the current file and remove upper comment to save changes!

package auth_module

type TokenIsValidBody struct {
	AccessToken string `json:"access_token" validate:"required"`
}
