// Code generated by gomarvin, v0.6.x. DO NOT EDIT.
// Rename the current file and remove upper comment to save changes!

package transaction_module

type CreateTransactionBody struct {
	SenderId   string `json:"sender_id" validate:"required,uuid4"`
	RecieverId string `json:"reciever_id" validate:"required,uuid4"`
	Amount     int32  `json:"amount" validate:"required"`
}
