// Code generated by gomarvin, v0.6.x. DO NOT EDIT.
// Rename the current file and remove upper comment to save changes!

package user_module

type RegisterUserBody struct {
	Username string `json:"username" validate:"required,min=5,max=250"`
	Password string `json:"password" validate:"required,min=10,max=250"`
	Email    string `json:"email" validate:"required,email"`
}

type LoginUserBody struct {
	Username string `json:"username" validate:"required,min=5,max=250"`
	Password string `json:"password" validate:"required,min=10,max=250"`
}
